import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      "build/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      // Archived third-party design export. Read-only historical record — never linted.
      "docs/design-source/**",
      // Regenerated by Next on every build; its triple-slash reference is not
      // editable at source.
      "next-env.d.ts",
      // Deno runtime with its own toolchain (`npm run test:edge`). The Node /
      // Next TypeScript rules here do not describe that environment.
      "supabase/functions/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // Underscore prefix is the project's convention for a deliberately
      // unused binding. The rule should honour it rather than flag it.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Public-site images are Supabase Storage objects served through short-TTL
      // signed URLs (CONSTRAINT-15). next/image cannot cache or optimise a URL that
      // expires, so plain <img> is the deliberate choice, not an oversight.
      "@next/next/no-img-element": "off",
    },
  },
];

export default eslintConfig;
